services:
  postgres:
    image: postgres:12
    ports:
      - 6432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:latest
    container_name: redis

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    depends_on:
      - api
      - client
    container_name: nginx
    restart: always
    ports:
      - 3050:80

  api:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    container_name: api
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres
      - PGPORT=5432

  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile.dev
    container_name: worker
    volumes:
      - /app/node_modules
      - ./worker:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    container_name: client
    volumes:
      - /app/node_modules
      - ./client:/app
    environment:
      - WDS_SOCKET_PORT=0

volumes:
  postgres-db-volume:
    driver: local
