name: Deploy
on:
  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      environment:
        description: environment
        type: environment
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Chekcout repository
        uses: actions/checkout@v4

      - name: deploying
        run: echo deploying...
